### ISSUE TITLE
Switch to GitHub actions

### ISSUE THREAD

**Issue by cmbuckley** [cmbuckley/cv#2]
Replace Travis Makefile targets with equivalent GitHub Actions.

Must handle:

- Build md and pdf (these should still use make as they are useful locally)
- Commit files to gh-pages branch
- Purge Cloudflare after success
- Update GitHub bio
- Create PR for role into main repo

Variables: https://damienaicheh.github.io/github/actions/2021/04/15/environment-variables-secrets-github-actions-en.html

**Comment by RishiKumarRay** [comment]
Can you elaborate this issue please

**Comment by cmbuckley** [comment]
Completed in 9e2f044f66cefb30df8a413f64bea6fbb7d19fc8...87e81877cdd587a85ede9acad444e088c1e6c38a.
